### ISSUE TITLE
[Feat] 다이어리 화면 구현 (기존 MyDiaryPages)

### ISSUE THREAD

**Issue by Dorodong96** [TwoInterval/MacC-GoldenRatio#108]
## 구현해야하는 요소들
- Custom Segmented Control
- 일차, 날짜, 사진을 담은 CollectionViewCell 구현
- Firebase에서 해당 일차의 사진을 랜덤하게 가져와서 viewDidLoad(혹은 viewWillAppear?)마다 띄우기
- Cell을 각 row로 담은 CollectionView 구현
++ 여유가 생기면 초대코드 복사 방법 변경하기

<br>

| 스크린샷1 | 스크린샷2 |
|:---:|:---:|
|![스크린샷1](https://user-images.githubusercontent.com/45297745/200306767-0ab40638-fd2a-4d6a-bbae-d49ef95aa55c.png)|![스크린샷2](https://user-images.githubusercontent.com/45297745/200306776-ba09f0b4-f066-463e-92f7-c053595a1ef7.png)|

<br>

## TODO
- [x] CollectionViewCell ViewModel 구현
- [x] CollectionViewCell View 구현
- [x] UICollectionView 구현
- [x] UICollectionView ViewModel 구현
- [x] Custom Segmented Control 구현
- [x] 랜덤하게 item의 image 타입 데이터를 띄워주기
- [x] Segmented Control에서 앨범 및 지도 뷰 띄우기

<br>

## 비고 및 한계
- RxSwift + MVVM 적용 예정
- 추후 시간에 따른 사진 전환 효과를 고려하여 CollectionView 채택
- 디폴트 이미지에 대한 픽스 필요
