### ISSUE TITLE
[Feat] DiaryConfigView 기능 추가 (컬러 선택, 사진 선택)

### ISSUE THREAD

**Issue by Dorodong96** [TwoInterval/MacC-GoldenRatio#109]
## 구현해야하는 요소들
- 컬러 선택 collection view 추가
- image picker 추가
- 선택하는 사진의 사이즈 조절 custom 기능 구현

<br>

## 구현 예시
디자인 픽스 후 추가

<img src="https://user-images.githubusercontent.com/45297745/200911332-210ea59c-d765-4057-b467-43759cee41fd.png" width="250" height="541"/>

 

<br>

## TODO
- [x] 컬러 선택 collection view 추가
- [x] image picker 추가
- [x]  완료 버튼 누르면 사진 데이터 업로드 (FireStorage)
- [x]  사진 데이터 다운로드 (String URL 사용)
- [x]  다운로드한 사진 데이터 수정 화면에서 띄우기
- [x]  ActionSheet 추가

<br>

## 비고 및 한계
- 아직 정확한 배치가 나오지 않아 디자인 확정 후 UI구현
