### ISSUE TITLE
[Feat] MyDiaryPagesView 구현

### ISSUE THREAD

**Issue by Dorodong96** [TwoInterval/MacC-GoldenRatio#11]
## 구현해야하는 요소들
- 글 페이지 구현
- Action Sheet 구현
- 초대 코드 생성 및 클립보드 복사
- 다이어리 수정 기능
- 다이어리 나가기 기능

<br>

## 구현 예시
| 다이어리 화면 | 다이어리 메뉴 화면 | 다이어리 수정 화면 |
|:---:|:---:|:---:|
|![다이어리 화면](https://user-images.githubusercontent.com/45297745/192927875-424231bc-62b9-4a5d-8539-e03e16a90f8f.png)|![다이어리 화면2](https://user-images.githubusercontent.com/45297745/192927889-6484abd5-eab9-4383-b7b8-c8657fe6c5a7.png)|![다이어리 수정 화면](https://user-images.githubusercontent.com/45297745/192927904-7233cd1d-6956-452e-aa78-ef80d3a35696.png)|

<br>

## TODO
- [x] 글 페이지 UI 구현 (CollectionView + ScrollViewDelegate)
- [x] ActionSheet 구현 (초대 코드 생성, 다이어리 수정)
- [x] 다이어리 생성이 아닌 수정할 내용을 담은 뷰 구현 (Title 변경)
- [x] 기존 다이어리 내용 Firebase에서 불러오기
- [x] 수정된 다이어리 내용 Firebase에 업로드
- [x] 다이어리 나가기 구현 (Firebase Extension - Delete User Data)
- [x] 다이어리 생성에서 저장된 diaryUUID활용, 초대코드 생성
- [x] 초대 코드 클립보드 복사 (UIPasteboard) 

<br>

## 비고 및 한계
- 상세 디자인은 아직 고려하지 않고 컴포넌트 기능 구현 위주
- 다이어리 페이지 내용은 더미데이터 활용 (썸네일)

**Comment by Dorodong96** [comment]
- [ ] 기기대응 추가 (상단 메뉴버튼 레이아웃 조정) `equalToSuperView()` -> `equalTo(버튼 레이아웃)`
<img src="https://user-images.githubusercontent.com/45297745/195232484-e90b0e98-9dca-42a9-8eed-64b18be52ca0.png" width="250" height="450"/>    
iPhone SE
