### ISSUE TITLE
[Add] add & fix assets

### ISSUE THREAD

**Issue by lau0505** [TwoInterval/MacC-GoldenRatio#121]
## 구현해야하는 요소들
- 수정된 다이어리 표지 이미지 에셋
- 다이어리 하단 표지 기본 이미지 에셋
- 일차별 기본 이미지 에셋

<br>

## TODO
- [x] 수정된 다이어리 표지 이미지 에셋 추가하기
- [x] 다이어리 하단 표지 기본 이미지 에셋 추가하기
- [x] 일차별 기본 이미지 에셋 추가하기

<br>

## 비고 및 한계
-
