### ISSUE TITLE
[Feat] Page 관련 화면 HIFI 디자인 반영

### ISSUE THREAD

**Issue by iDrogba** [TwoInterval/MacC-GoldenRatio#133]
## 구현해야하는 요소들
- Page 관련 화면 HIFI 디자인 반영

<br>

## TODO
- [x] Page view mode 화면
- [x] Page edit mode 화면
- [x] text sticker view 입력 모드 배경 색
- [x] my page 화면

<br>
