### ISSUE TITLE
[Design] 세부 UI 수정 (Toast Message, Segmented Control, Calendar)

### ISSUE THREAD

**Issue by Dorodong96** [TwoInterval/MacC-GoldenRatio#140]
## 구현해야하는 요소들
- Toast Message 크기 및 위치 수정
- Segmented Control 전반적인 UI 수정
- Calendar 년 / 월 한글로 변경

<br>

## 구현 예시

 

 

<br>

## TODO
- [x] Toast Message 크기 및 위치 수정
- [x] Segmented Control 전반적인 UI 수정
- [x] Calendar 년 / 월 한글로 변경

<br>

## 비고 및 한계
-
