### ISSUE TITLE
[Design] 디자인 수정

### ISSUE THREAD

**Issue by iDrogba** [TwoInterval/MacC-GoldenRatio#143]
## 구현해야하는 요소들
- 마이 페이지 background color 변경
- 마이페이지 textfield placeholder 넣기
- 마이페이지 프로필이미지 세팅 버튼 위치 수정
- 페이지 보기화면 일차 변경 시 spacing 변경
<br>

## TODO
- [x] 마이 페이지 background color 변경
- [x] 마이페이지 textfield placeholder 넣기
- [x] 마이페이지 프로필이미지 세팅 버튼 위치 수정
- [x] 페이지 보기화면 일차 변경 시 spacing 변경

<br>
