### ISSUE TITLE
[Add] 에셋 추가 및 수정

### ISSUE THREAD

**Issue by lau0505** [TwoInterval/MacC-GoldenRatio#156]
## 구현해야하는 요소들
- 반팔 캐릭터들도 포즈 그려서 추가
- 각 이미지들 크기 맞춰서 재수정 후 재추가
- 여권 스티커 디자인 재수정
- 스티커 요소 더 추가
- 지도 리스트에 나올 디폴트 카테고리 아이콘 디자인 후 에셋 추가
 
<br>

## 구현 예시

<img width="448" alt="stickers" src="https://user-images.githubusercontent.com/103024956/202850117-804e694c-6812-47e9-8ab1-d05ae89db86b.png">
<img width="370" alt="스크린샷 2022-11-19 오후 9 11 08" src="https://user-images.githubusercontent.com/103024956/202850299-4b9c0868-1555-4aea-ae4a-1925ad523d28.png">
    

<br>

## TODO
- [x] 각 반팔 캐릭터 포즈 추가해서 그리기
- [x] 각 이미지들 크기 및 비율 맞추기
- [x] 여권 스티커 디자인 재수정하기
- [x] 스티커 요소 더 추가하기
- [x] 지도 리스트에 나올 디폴트 카테고리 아이콘 디자인하기

<br>

## 비고 및 한계
-
