### ISSUE TITLE
[Feat] 새로운 ImagePickcer 기능 추가

### ISSUE THREAD

**Issue by iDrogba** [TwoInterval/MacC-GoldenRatio#166]
## 구현해야하는 요소들
- ImageSticker 추가 시 사진 여러장 추가 기능
- 사진 첨부 시 원하는 프레임으로 잘라 넣을 수 있는 기능 (Crop 기능)

<br>

## TODO
- [x] 라이브러리 선택하기
- [x] 앱 내 ImagePicker 사용 화면들의 요구사항 분석하여 클래스 생성
- [x] 사진 여러장 추가 기능
- [x] 사진 Crop 기능

<br>

## 비고 및 한계
- 외부 라이브러리를 추가하여 구현합니다.
