### ISSUE TITLE
[Feat] DiaryDaysView 일차별 대표 이미지 설정

### ISSUE THREAD

**Issue by Dorodong96** [TwoInterval/MacC-GoldenRatio#167]
## 구현해야하는 요소들
- 일차별 대표 이미지 설정 기능 추가
- 일차별 이미지 선택 CollectionView 추가
- 선택된 이미지는 pageThumbnail 항목으로 설정

<br>

 

<br>

## TODO
- [x] 일차별 대표 이미지 분기 처리 (thumbnail이 없는 경우 -> 랜덤 / 있는 경우 -> 해당 이미지로 설정)
- [x] 디자인 나오는대로 CollectionView 추가
- [x] @iDrogba 화면에 PopupView 버튼 & 액션 추가
- [x] 모달로 해당 뷰 띄우고 적용 확인

<br>

## 비고 및 한계
-
