### ISSUE TITLE
[Add] 에셋 추가

### ISSUE THREAD

**Issue by lau0505** [TwoInterval/MacC-GoldenRatio#170]
## 구현해야하는 요소들
- minus 버튼 커스텀 아이콘 추가
- 지도 핀 아이콘 수정
- 스티커 도구, 텍스트 도구 아이콘 수정

## TODO
- [x]  minus 버튼 커스텀 아이콘 추가하기
- [x] 변경된 지도 핀 아이콘 추가하기
- [x] 변경된 스티커 도구, 텍스트 도구 아이콘 추가하기

<br>

## 비고 및 한계
-
