### ISSUE TITLE
[Refactor] UIColor 수정

### ISSUE THREAD

**Issue by Dorodong96** [TwoInterval/MacC-GoldenRatio#187]
<br>

## TODO
- [x] Asset 폴더링 (폴더는 대문자, 이미지/컬러 이름은 smallCamelCase)
- [x] Asset의 다크모드 컬러 전부 제거
- [x] 컬러 이름 선정 및 UIColor+ 항목 통일
- [x] 수정된 컬러 반영

<br>
