### ISSUE TITLE
[Add] 에셋에 추가할 요소

### ISSUE THREAD

**Issue by lau0505** [TwoInterval/MacC-GoldenRatio#35]
## 구현해야하는 요소들
- 탭 바 아이콘
- 앱 캐릭터 (긴팔,반팔 ver.)
- 플러스 버튼
- 앱 배경 이미지
- 다이어리 속지 이미지
- 다이어리 표지 이미지 10장
- 스티커 예시 (일단 최소 1장...)

<br>

## 구현 예시

<img src="https://user-images.githubusercontent.com/45297745/192956478-271f2f03-4cea-4497-9e82-84f91fad8ba5.png" width="250" height="541"/>

 

<br>

## TODO
- [x] 탭 바 아이콘 픽스하기
- [x] 앱 캐릭터 (긴팔,반팔 ver.) 픽스하기
- [x] + 버튼 픽스하기
- [x] 앱 배경 이미지 픽스
- [x] 다이어리 속지 이미지 픽스
- [x] 다이어리 표지 이미지 컬러시트 10장 픽스하기
- [x] 스티커 예시 픽스하기

<br>

## 비고 및 한계
- 항시 업데이트 해두고 있으니 전체적으로 디자인 패턴이 궁금하시다면 피그마 내 "디자인 시스템 가이드" 페이지를 참고해 주심 됩니다.
- 오늘 내 작업한 디자인들은 내일 산 및 개발 팀원들과 다같이 확인 및 회의 후 픽스 짓기

**Comment by Dorodong96** [comment]
내일 캘린더 UI/UX도 얘기해보아요~😄😂😭

**Comment by lau0505** [comment]
완료
