### ISSUE TITLE
[Faet] QA 수정사항 반영

### ISSUE THREAD

**Issue by woo0dev** [TwoInterval/MacC-GoldenRatio#58]
## 구현해야하는 요소들
- 로딩 인디케이터 구현
- 앨범 타이틀 크기 조절
- 앨범 페이징 수정
- Data Fetch 타이밍 수정
- 앨범 백그라운드 뷰 수정
- 토스트 메세지 추가
- 지도 어노테이션 이미지 변경
- collectionBackgroundView 폰트 수정
- 타이틀 색상 적용

<br>

## 구현 예시

 
| 앨범화면 | 지도화면 |
|:---:|:---:|
| <img src="https://user-images.githubusercontent.com/57060443/195795989-aa1e43f2-4dda-46c9-9b39-5b2b90802df6.png" width="250" height="541"/> | <img src="https://user-images.githubusercontent.com/57060443/195796900-2acb1467-7e43-46b4-9ea0-ceaab0072268.png" width="250" height="541"/> |

## TODO
- [x] 로딩 인디케이터 구현
- [x] 앨범 타이틀 크기 조절
- [x] 앨범 페이징 수정
- [x] Data Fetch 타이밍 수정
- [x] 앨범 백그라운드 뷰 수정
- [x] 토스트 메세지 추가
- [x] 지도 어노테이션 이미지 변경
- [x] collectionBackgroundView 폰트 수정
- [x] 타이틀 색상 적용

<br>

## 비고 및 한계
-
