### ISSUE TITLE
[Feat] 22.10.16 PR Merge 이후 작업 예정 사항

### ISSUE THREAD

**Issue by Dorodong96** [TwoInterval/MacC-GoldenRatio#61]
## TODO
- [x] 토스트 팝업 띄우기 (다이어리 작성/수정 확인 버튼, 초대코드 복사 완료)
- [x] 다크모드 대응 - 다크모드를 아예 없애기? 각각의 컬러 대응하기?
- [x] 다이어리 수정 이후 타이틀 변경

<br>

## 비고 및 한계
-다크모드 대응의 경우, 앱에서 아예 막는 방법은 어떤가요? 추후에 다크모드가 있는 버전 제작을 고려한다면 지금 다크모드가 지원되지 않게 막고 이후 다크모드에 맞는 디자인으로 다시 다시 변경하는 것도 생각해 볼 수 있을 것 같습니다!
