### ISSUE TITLE
[design] 에셋에 추가 수정 요소들

### ISSUE THREAD

**Issue by lau0505** [TwoInterval/MacC-GoldenRatio#66]
## 구현해야하는 요소들
- 앱 로고 컬러 수정
- 로그인 화면에 나오는 앱 로고 컬러 수정
- 다이어리 표지 핑크,브라운 컬러 수정

## TODO
- [x] 앱 로고 컬러 수정하기
- [x] 로그인 화면에 나오는 앱 로고 컬러 수정하기
- [x] 다이어리 표지 핑크,브라운 컬러 수정

<br>

## 비고 및 한계
-
