### ISSUE TITLE
[Feat] MyPlacesView 구현

### ISSUE THREAD

**Issue by woo0dev** [TwoInterval/MacC-GoldenRatio#7]
## 구현해야하는 요소들
- MapView 구현
- Marker 구현
- Unit Test
<br>

## 구현 예시
<img src="https://user-images.githubusercontent.com/57060443/192844184-0d5f8f9a-0d7a-47de-b38e-6d223560daa2.png" width="250" height="541"/>
<br>
 
## TODO
- [x] MapKit을 활용하여 MapView 구현
- [x] 다이어리의 Location을 바탕으로 Marker 추가 및 겹치는 Marker는 하나로 통합하여 개수 보여주기
- [ ] Class와 Function을 Unit Test를 활용하여 오류를 체크하고 성능 체크하기
<br>

## 비고 및 한계
- 다이어리 추가 기능 작업 완료 전까지는 더미데이터를 활용할 예정입니다.
