### ISSUE TITLE
[Feat] MyAlbumsView

### ISSUE THREAD

**Issue by woo0dev** [TwoInterval/MacC-GoldenRatio#8]
## 구현해야하는 요소들
- 여행 별 ScrollView (horizontal)
- CollectionView
- Unit Test

<br>

## 구현 예시
<img src="https://user-images.githubusercontent.com/57060443/192845312-35bc38c5-b9c9-46ef-a0a7-4b38bfcf3414.png" width="250" height="541"/>
 
<br>

## TODO
- [x] 다이어리의 타이틀을 활용해 여행 별 앨범 구현하기 (horizontal scroll view)
- [x] Firebase Storage에 있는 다이어리 별 사진을 가져와 CollectionView로 구현하기
- [ ] Class와 Function을 Unit Test를 활용하여 오류를 체크하고 성능 체크하기

<br>

## 비고 및 한계
- 다이어리 작성 기능 완료 전까지는 더미데이터 활용하여 작업 예정
