### ISSUE TITLE
[Feat] SignInView 구현

### ISSUE THREAD

**Issue by Dorodong96** [TwoInterval/MacC-GoldenRatio#9]
## 구현해야하는 요소들
- Apple ID SignIn 버튼 구현
- 로그인 기능 구현

<br>

## 구현 예시
<img src="https://user-images.githubusercontent.com/45297745/192918693-e868e9f5-88ba-4bda-ac46-f4d6e8ca2b76.png" width="250" height="541"/>
 
<br>

## TODO
- [x] Firebase Auth Configuration 하기
- [x] Apple ID SignIn 버튼 UI 구현하기
- [x] Apple ID SignIn 기능 구현
- [x] Firebase에 계정 정상 등록 여부 확인

<br>

## 비고 및 한계
- 버튼 포함 상세 UI는 Hi-Fi 디자인이 나오는대로 추가 및 수정
