### ISSUE TITLE
[Fix] HIFI 반영하여 수정

### ISSUE THREAD

**Issue by iDrogba** [TwoInterval/MacC-GoldenRatio#95]
## 구현해야하는 요소들
- 페이지에서 지도 라벨 색깔 수정
- 네비게이션 바 타이틀 수정
-  마이페이지 타이틀 컬러 수정
- 지도 스티커 라벨 수정
-  스티커 피커 X 수정

<br>

## TODO
- [x] 페이지에서 지도 라벨 색깔 수정
- [ ] 네비게이션 바 타이틀 수정
- [x] 마이페이지 타이틀 컬러 수정
- [x] 지도 스티커 라벨 수정
- [x] 스티커 피커 X 수정

<br>

## 비고 및 한계
-
